apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xapp-namespace
spec:
  compositeTypeRef:
    apiVersion: platform.ronald.dev/v1alpha1
    kind: XApp

  mode: Pipeline
  pipeline:
    - step: create-namespace
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - name: namespace
            base:
              apiVersion: v1
              kind: Namespace
              metadata:
                name: placeholder
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.namespace
                toFieldPath: metadata.name