apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-portal
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://github.com/RonaldLePape/internal-developer-platform-demo.git
    targetRevision: main
    path: environments/local/platform/portal
  destination:
    server: https://kubernetes.default.svc
    namespace: platform-portal
  syncPolicy:
    automated:
      prune: true
      selfHeal: true