apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  description: Platform components
  sourceRepos:
    - https://github.com/RonaldLePape/internal-developer-platform-demo.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: workloads
  namespace: argocd
spec:
  description: Application workload declarations
  sourceRepos:
    - https://github.com/RonaldLePape/internal-developer-platform-demo.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: "*"
  clusterResourceWhitelist:
    - group: platform.ronald.dev
      kind: XApp